### PR TITLE
Add css boilerplate

### PR DESCRIPTION
**Pull request by justinvdm**
Last step for #5.

### CODE REVIEW

**Comment by justinvdm** [comment]
@SteveBarnett ready for review.

**Comment by SteveBarnett** [comment]
Just got one comment about the css.

``` javascript
files: {
          'static/css/collection-core.min.css': [
            'src/styles/views/collection/core.scss'
          ],
          'static/css/collection-enhanced.min.css': [
            'src/styles/views/collection/enhanced.scss'
          ]
        }
```

I don't think we want it this granular, do we?
I usually do something more like this:

``` javascript
files: {
          'static/css/core.min.css': [
            'src/styles/core.scss'
          ],
          'static/css/enhanced.min.css': [
            'src/styles/enhanced.scss'
          ]
        }
```

With sass partials like `_collections.scss` that get (sass) `@import`ed into core or enhanced.
It depends how big those partials are, but usually it makes sense to just bundle them in with the main CSS file: one and done.

**Comment by justinvdm** [comment]
@SteveBarnett the way we have things at the moment, we have a server-side template, bit of client-side js, a core stylesheet and enhanced stylesheet per page (or 'view', as I've been wording it in the repo so far). `collection-core.css` and `collection-enhanced.css` are stylesheets for the collection page (not the collection component, that's one component that would exist on the collection page, as would a block component, for example). Its likely that pages will share styles and js though, so maybe we should take a different approach. Thoughts?

**Comment by SteveBarnett** [comment]
As discussed at The Whiteboard in The Dev Cave, let's bundle CSS into one big one (and keep per view bundles for the js).

:+1:

**Comment by justinvdm** [comment]
Ready for re-review.

**Comment by SteveBarnett** [comment]
Bueno! :+1:

**Pull request merged**
